# Generated by Django 4.2.3 on 2023-08-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
